### ISSUE TITLE
Run addin dlls as much as Dynamos and Python scripts 

### ISSUE THREAD

**Issue by Babuh** [bvn-architecture/RevitBatchProcessor#22]
I can see in your UI that you can run python scripts and dynamos but C# Revit addins are missing, will it be added in the future or do I have to translate to python my existing C# scripts ?
Thanks !

**Comment by DanRumery** [comment]
Hi @Babuh 

Actually using a python script it's quite easy to load and execute code in a C# DLL. When RBP runs the python task script, it adds the task script's folder path to the search paths so that **if your DLL is in the same folder as your python task script you should be able to do something like the following**:

```
# For example assume your DLL is called MyUtilities.dll and you have a static function called SomeClass.DoSomeWork() in namespace MyNameSpace:
# Assume this python script exists in the same folder as MyUtilities.dll.
clr.AddReference("MyUtilities")
from MyNameSpace import SomeClass

# Invoke your function, passing in any parameters you need
SomeClass.DoSomeWork(doc)
```

Perhaps I could look at allowing for a DLL to function as a task script directly but it requires a fair bit of careful logic (e.g. the DLL would need to implement some task interface and RBP would have to inspect the DLL for correct implementations, loading them and executing them.)

Let me know if you find the python code workaround works...

**Comment by Babuh** [comment]
Hi @DanRumery 
Thanks a lot ! 
I'm trying this out right now !
