### ISSUE TITLE
Does RevitBatchProcessor run cloud based models (BIM 360 Teams/Docs)?

### ISSUE THREAD

**Issue by HAO-BSM** [bvn-architecture/RevitBatchProcessor#30]
Can RevitBatchProcessor run cloud based models (BIM 360 Teams/Docs)?

When opening a BIM360 project options to Detach/Create Local are disabled (grayed out) on Cloud Based Models. If Cloud Models can be open via RevitBatchProcessor can it detach? 
or do we need to access via local Collaboration Cache. 
(C:\Users\<user>\AppData\Local\Autodesk\Revit\Autodesk Revit 2018\CollaborationCache).

Thanks for your efforts. Such a powerful tool!

**Comment by DanRumery** [comment]
At the moment it won't work with cloud based model paths but I will add it to the TO DO list! I believe in Revit 2019 API it will accept BIM360 paths as input so I'll do some testing over the next week or so.

Will keep you posted.

And thanks you're welcome :)

**Comment by DanRumery** [comment]
@HAO-BSM Sorry I haven't got back to you sooner on this. It seems I would have to use the Forge API in order to perform certain kinds of operations on Teams/BIM360 files as the Revit API partially supports querying cloud-based models but not enough to perform operations on Central files.

I'll still investigate this further but in the meantime your suggested workaround using the `CollaborationCache` folder sounds like it's a decent workaround if you already have the local files on hand. Not ideal though.

**Comment by archinfo82** [comment]
Hi ~
How to debug a python code? 
Could not debug using visual studio attach to process.
Thanks in advance!

**Comment by DanRumery** [comment]
@archinfo82 Hi there

This would be best opened as a separate question/issue.

But to answer the question, unfortunately there isn't a way to debug python code running in Revit.

**Comment by DanRumery** [comment]
There is now limited support for processing BIM360 hosted Revit files. See the README for more info.
