### ISSUE TITLE
Bug: Use same Revit session not working on 2016

### ISSUE THREAD

**Issue by infeeeee** [bvn-architecture/RevitBatchProcessor#37]
I select 'Use same Revit session' but after processing one file Revit closes, and the new file processed in a new session. 

I expected that using this option Revit won't close after processing one file but open the new file in the same session, or am I misunderstanding this option?

I found this bug running a dynamo script on Revit 2016

Around the beginning of the log file it says: 
```
21. 05. 2019 18:05:49 : Revit Processing mode:
21. 05. 2019 18:05:49 : 
21. 05. 2019 18:05:49 : 	Batch Revit File processing
```

Screenshot of my settings:
![image](https://user-images.githubusercontent.com/1271737/58115227-ecb70000-7bf9-11e9-813e-f6a02b0612e0.png)

**Comment by DanRumery** [comment]
Hi @infeeeee 

Yeah you're right about this but actually a known issue when using a Dynamo task script (under 'Known Limitations / Issues' in the Readme.)

That setting actually only works for python task scripts, the reason being I wasn't able to manipulate multiple documents from multiple Dynamo scripts in the same Revit session.

I should make it so that option is grayed out if a Dynamo task script is selected. Sorry for the confusion there!

**Comment by infeeeee** [comment]
Oh, sorry my bad, I didn't read the documentation carefully.

Graying out that option would be a nice touch!

**Comment by DanRumery** [comment]
I've added an issue (#38) to disable this option in the UI when a Dynamo task script has been selected.
