### ISSUE TITLE
Feature Request: Make RBP skip the CentralModelException and open the file anyway

### ISSUE THREAD

**Issue by btokmyrza** [bvn-architecture/RevitBatchProcessor#39]
![CentralModelExceptionCensored](https://user-images.githubusercontent.com/29689547/59019517-04cd8700-886a-11e9-9ded-901b45b38d06.png)

**Comment by DanRumery** [comment]
Hi @btokmyrza 

I tried to setup this scenario to see if I get the same exception but I couldn't replicate the behaviour. How did you achieve this particular dialog box?

The other possibility here is that because RBP is language-dependent when it comes to automatically clicking the dialog box buttons, it may be missing this dialog box due to the different text on the button.

Keen to hear more information from you...

**Comment by DanRumery** [comment]
Issue seems to be abandoned. Will re-open if there is feedback.
