### ISSUE TITLE
Where is Excel file processed?

### ISSUE THREAD

**Issue by RyanSchw** [bvn-architecture/RevitBatchProcessor#40]
I'm looking at contributing to this project, but I'm a bit confused on where the excel file is processed. The only references I found to Microsoft Office dlls are in `excel_util.py`, but I'm not sure how that plays into the larger script.

Overall goal was to additionally support `.csv` input as well, so I was going to try to use a similar model to how `.xlsx` and `.txt` files are processed now.

Additionally, it would be helpful for a "Getting Started" section for Contributors. I'll be able to help out on that once I figure it out myself :)

**Comment by DanRumery** [comment]
Hi Ryan

The module you'll want to look at is `BatchRvtUtil\Scripts\revit_file_list.py` which handles reading the Revit file list. You'll see the `excel_util` module is imported dynamically in the function `FromExcelFile()`. This is due to the possibility that Excel may not be installed on the users' system. 
 You'll also see `BatchRvtUtil\Scripts\text_file_util.py` is used to load the list from a tab-delimited file. You could probably add csv support by modifying these two files (`revit_file_list.py` and `text_file_util`).

I agree an overview would be handy. I'm busy at the moment but I'll add it as an issue.
