### ISSUE TITLE
Passing uiapp to C#/vb.net not working ... 

### ISSUE THREAD

**Issue by rayray4105** [bvn-architecture/RevitBatchProcessor#49]
Hi,

I am trying to run a C#/vb.net dll using RBP (in Revit 2018 and 2019). The dll is loaded and initialy the routine executes just fine when just passing 'doc' (doc = revit_script_util.GetScriptDocument()). No errors occur when only doc is used in my dll.

However if I also use 'uiapp' (uiapp = revit_script_util.GetUIApplication()) in my code to pass uiapp to uidocument (UIDocument uiDoc = uiapp.ActiveUIDocument;) I get an error: object not set to an instance of an object. Could uiapp be empty? Or is there another way to get uidocument directly?

I have also tried to modify the python script by adding:
uidoc = uiapp.ActiveUIDocument() but that results in another error: NoneType is not callable. 

Am I missing something or could uiapp be emtpy/not found?

**Comment by DanRumery** [comment]
That is odd as I've just tested the variable in my own script and it does return the UIApplication instance.   Perhaps can you send a sample of the task script that causes this error?

Also which version of RBP are you using?

**Comment by DanRumery** [comment]
Actually it's possible that because the document is not opened visibly in the UI, that ActiveUIDocument is null. RBP only opens the document in the UI when running a Dynamo task script.

I'm guessing you would have to do an [UIApplication.OpenAndActivateDocument()](https://www.revitapidocs.com/2019/5018fbdb-e7c3-6e32-7ca3-ee5c20dbc56f.htm) first, passing the Revit file path converted to a ModelPath to the function. If the file is already detached though, then this would require first saving it as the function can't activate the document in the UI without a file path...

There is actually a hidden setting "openInUI" that you can find if you export RBP settings json file and inspect the file in a text editor. You could try setting that property to True to force python scripts to open the document in the UI.

Let me know if it helps...

**Comment by DanRumery** [comment]
Assuming you got this working because I can't replicate the issue. Closing for now.
