### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jeremytammik** [bvn-architecture/RevitBatchProcessor#51]
Thank you for this impressive utility. 

I shared it on The Building Coder: 

https://thebuildingcoder.typepad.com/blog/2019/11/the-revit-batch-processor-rbp.html

Questions:

- Are the actions taken automatically logged? Why? In case of a problem, it might be handy to know how far you got successfully before the problem appeared, so that you know where to pick up again.

- Is the Revit.exe health monitored? Why? Well, Revit is not built for batch processing, so one might expect it to crash and die if it is force fed too many files in a single session.

- Is Revit restarted for each new document? That would reduce the risk of the aforementioned point.

Thank you!

Cheers, 

Jeremy

**Comment by DanRumery** [comment]
@jeremytammik 

Hi Jeremy, many thanks for sharing it!

1) There is a log file that records the consoles output seen in the GUI. (Log files by default are written to the folder `%APPDATA%\BatchRvt`). It logs stuff like process Revit startup and monitoring, files processed, file actions (open, closing, detach, file type, path, etc). But any custom actions performed by a script would be left up to the script to record action-specific progress. If using a python script there is a utility function `Output()` for logging to RBP's console. Dynamo scripts would need their own mechanism for logging, however.

2) The Revit process(es) are monitored to detect process exit and process busy events. This info is logged to the console. If a Revit session crashes, RBP starts up a fresh Revit session for any files that remain to be processed (so only the Revit file that lead to the crash will be skipped). Indeed I found this can happen when processing a large amount of Revit files hence the recovery mechanism. You'll see in the UI there is an option to process the files in the same Revit session (when possible) or process every file in its own session but as far as crash recovery is concerned, the behaviour is the same. Note that Dynamo scripts are always made to run in a separate Revit session per file due to some limitations I encountered when closing an active UI document, but python scripts don't have this limitation and hence will process a lot faster!

3) See 2) :)

**Comment by DanRumery** [comment]
There is also a per-file time-out feature that can be used to terminate processing of a file if the time limit is reached. In that scenario the Revit process is forcibly terminated and a fresh session started up to process the remaining files.

**Comment by jeremytammik** [comment]
Wow, that sounds very professional indeed! Congratulations! Thank you for your kind answers. I added them to the blog post: https://thebuildingcoder.typepad.com/blog/2019/11/the-revit-batch-processor-rbp.html#8
