### ISSUE TITLE
processing central files

### ISSUE THREAD

**Issue by ericenagel** [bvn-architecture/RevitBatchProcessor#74]
Hello.  I am attempting to process a list of 25 central files (opened as local, not detaching from central) and I receive the following repeating message occasionally.  What may be going on?

22:10:16 : Revit dialog box detected!
22:10:16 : 
22:10:16 : 	Dialog box title: 'Local Changes Not Synchronized with Central'
22:10:16 : 
22:10:16 : 	Button: 'Synchronize with central'
22:10:16 : 
22:10:16 : 	Button: 'Close the local file'
22:10:16 : 
22:10:16 : 	Button: 'Cancel'
22:10:16 : 
22:10:16 : WARNING: Could not find suitable button to click.

**Comment by DanRumery** [comment]
Hi @ericenagel 

This is probably because your Dynamo script needs to synchronize to the central file. There are several Dynamo packages out there with the Synchronize functionality. I originally thought of adding a synchronize option directly in RBP but was concerned about accidental use of it (since choosing to synchronize to central requires careful consideration).

As you can see there RBP will close the local file without synchronizing, but that message won't appear if your Dynamo script performs the Synchronize (with a node). Let me know if any questions about that. I think I mentioned it in the FAQ but it's easy to miss.

**Comment by ericenagel** [comment]
Thanks for the reply.  Interestingly enough, of the 25 files that I was processing only 5 got caught in this loop of not being able to find a suitable button to click.  As far as the nodes go, I do not believe that I am using any that are initiating a sync function.

Would processing the files as detached make any difference?

[cid:Logo_CushingTerrell_Sig_c8278f6f-8f3f-45ad-8476-3bbae351291a.png]
[cid:LinkedIn_icon_teal_eab3e198-ada5-4916-b445-7ab6a45a1183.png]       [cid:Twitter_icon_teal_7116b3e6-4583-4d6e-8764-aaf20e227c84.png]        [cid:Instagram_icon_teal_231c6090-3632-4fca-844f-5c96ef34c32f.png]      [cid:Facebook_icon_teal_7dd3ce24-c562-45c4-b38a-2f74c2be7031.png]


Eric Nagel
BIM Coordinator
[cid:Phone_icon_teal_ec4e89bf-1bf7-4941-9490-c24b3fe13977.png]  512.872.3019<tel:512.872.3019>  [cid:Website_icon_teal_c1c2bcac-4de5-47f3-b080-9309a44f8ab4.png]        cushingterrell.com<http://www.cushingterrell.com/>

CTA is now Cushing Terrell.

**Comment by DanRumery** [comment]
@ericenagel Yes the catch with using "create new local" is that you'd be expected to synchronize the local file if any changes were made (possibly whatever operation you performed indirectly modified those 5 files so Revit prompted for a save or sync). If you do need to create a local file but don't want to sync it (and avoid the prompt) it'd probably work to close the document at the end of your script. But if you use detach you won't have to worry about it (as you found out).
