### ISSUE TITLE
'Use same Revit session for Revit files of same Revit Version' is greyed-out

### ISSUE THREAD

**Issue by paulmst** [bvn-architecture/RevitBatchProcessor#87]

**Comment by punderscoresmithuk** [comment]
Hi @paulmst is this still a problem? Can you provide a snip of your GUI or abit of information about the environment you're trying to run RBP in/from?

**Comment by ShinK360** [comment]
Hi. Thank you for this great app. This is an awesome tool indeed!
I installed the latest (1.9 Beta). Thanks again for upgrade. I am currently having the same issue. The option is greyed out.

![2022-12-13 12 44 45](https://user-images.githubusercontent.com/104182852/207185176-45740d91-fc0e-4826-8b20-444691ae8678.png)

**Comment by punderscoresmithuk** [comment]
Thanks @ShinK360 

Can you provide a snip of the full GUI so I can see the other settings?

Are you trying to load a dynamo graph? Because that has to use a separate Revit session for each file

Cheers, Pete

**Comment by ShinK360** [comment]
Hi Peter

Thank you for coming back to me.
Here is the screen shot. I run a Dynamo script that QA and export data to Excel file on multiple Revit models in different Revit Versions from both Local and BIM360. It actually doesn’t matter if the models are from cloud or local, the option is always greyed out since the previous version. I hope I was not doing anything wrong.

***@***.***

Ngā Mihi

Shin Kameyama |  BIM Manager

architectus™ |  ***@***.*** <https://www.instagram.com/architectus.nz/>   | +64 9 307 5970  |  Auckland - Christchurch - Wellington  |   www.architectus.co.nz<http://www.architectus.co.nz/>

**Comment by punderscoresmithuk** [comment]
Hi @ShinK360 

The screenshot didn't come through for me unfortunately but I think I can see the problem here. Whenever you are using a dynamo file for your task script RBP can only execute them in separate Revit sessions. 

See the below excerpt from the Known limitations/issues section of the repository:

_Dynamo scripts will always be executed using the 'Use separate Revit session for each Revit file' option. This restriction is due to the context in which Revit Batch Processor operates with the Revit API, which prevents the active UI document from being closed or switched during the Revit session. (NOTE: When executing a Dynamo task script, the Revit Batch Processor opens the document in the UI and is therefore subject to this Revit API limitation. For Python task scripts, the Revit Batch Processor only opens the document in memory, so Python scripts do not suffer this restriction!)_

I'll close this issue because it is a known limitation when working with the Revit API. Please do log any bugs in the future though

Cheers, Pete
